Gueram/bikebox

app/models/boxbike.rb, app/models/contract.rb, app/models/user.rb, db/migrate/20201116164707_add_a_default_value_to_chargeoption_in_boxbike.rb, db/migrate/20201116165608_add_a_default_value_to_chargeoption_to_boxbike.rb, db/migrate/20201116172904_add_name_to_users.rb, db/schema.rb
=> validations_ok

Gemfile, Gemfile.lock, app/views/boxbikes/index.html.erb, db/seeds.rb
Created seed for 5 users + 5 boxbikes (with destroy_all)
Update view index
=> Seed user and box bikes and update index

app/controllers/boxbikes_controller.rb, app/views/boxbikes/index.html.erb, app/views/boxbikes/show.html.erb, config/routes.rb
=> show boxbike

app/controllers/boxbikes_controller.rb
devise was blocking the path  /boxbikes (index) to be accessible without login
change made
now /home and /boxbikes are accessible without login
=> /boxbikes accessible without login

app/controllers/boxbikes_controller.rb, app/views/boxbikes/new.html.erb, config/routes.rb, db/seeds.rb
Boxbikes controller new et create
View new boxbike done with form ok
=> Boxbikes controller setup

app/controllers/boxbikes_controller.rb, app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/views/boxbikes/show.html.erb, config/routes.rb
=> duplicate a revoir

app/views/boxbikes/index.html.erb, app/views/boxbikes/new.html.erb, app/views/boxbikes/show.html.erb, app/views/pages/home.html.erb
I added **link**s to navigate through existing pages and also added **containers** for a better display
=> added links and containers to existing pages

app/views/boxbikes/index.html.erb
J'ai ajouté le link_to sur l'adresse des boxbikes.
Comments welcome :)
=> added link to for boxbikes view index

app/controllers/contracts_controller.rb, test/controllers/contracts_controller_test.rb
=> Contract creation

app/controllers/boxbikes_controller.rb, app/views/boxbikes/show.html.erb
made destroy action fior boxbikes (updated boxbikes controller and show accordingly)
=> destroy boxbikes

app/views/shared/_navbar.html.erb
=> navbar try outs

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/boxbikes_controller.rb, app/policies/application_policy.rb, app/policies/boxbike_policy.rb, app/views/boxbikes/index.html.erb, app/views/boxbikes/show.html.erb, test/policies/boxbike_policy_test.rb
Pundit created for bikebox (index, show, update, create, edit, new, destroy) and views updated also
Works locally
=> pundit_ok_en_local

app/controllers/boxbikes_controller.rb
Changed the place of the @autorize for the delete method for boxbike
=> pundit_updated_for_Boxbike

app/controllers/contracts_controller.rb, app/views/boxbikes/show.html.erb, app/views/contracts/index.html.erb
=> contracts index view finish

app/controllers/contracts_controller.rb, app/policies/contract_policy.rb, test/policies/contract_policy_test.rb
Added pundit code for the model contract, for the methods index, new and create
=> pundit_contract_ok

app/controllers/application_controller.rb, app/controllers/contracts_controller.rb, app/policies/application_policy.rb, app/views/boxbikes/show.html.erb, app/views/contracts/index.html.erb, config/routes.rb
=> Destroy contracts

app/controllers/application_controller.rb, app/controllers/contracts_controller.rb, app/policies/contract_policy.rb, app/views/contracts/index.html.erb
pundit coded for the model Contract for the method destroy
And some minor changes in the Contract index view
=> pundit_contracts_ok

app/controllers/contracts_controller.rb, app/models/boxbike.rb, app/views/boxbikes/show.html.erb, app/views/contracts/index.html.erb
Added a method in model controller to calculate number of spots left in a box (capacity - number of spots rented)
Spots left displayed in boxbikes show, (place of display can be modified).
Other "modifs" are just indentation changes
=> User story org

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Dropdown modifié et navbar tweakée
J'ai commencé à bosser sur la banner aussi
=> navbar workout and dropdown and banner tweaks

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_main-container.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
Le footer est fait et fonctionne normalement (il reste bien tout en bas de la page sur toutes les views ;) )
=> footer done

app/views/shared/_navbar.html.erb
integrated Jack's dashboard route
=> dashboard in dropdown done

app/assets/stylesheets/components/_card_index_boxbikes.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_container_boxbike_index.scss, app/views/boxbikes/index.html.erb
=> cards index boxbike in progress

app/assets/stylesheets/pages/_container_boxbike_index.scss, app/views/boxbikes/index.html.erb
c'est moche, mais la maps et liste are side by side!
je cleanerais mon code apres aussi x
=> map and box list side by side in index bookings

app/views/boxbikes/new.html.erb
Did not create modal but made some changes to to boxbike new
=> some changes to boxbike new

app/assets/stylesheets/components/_card_index_boxbikes.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_container_boxbike_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/boxbikes/index.html.erb
pas fini, mais bon, ça donne une idee.
Je suis pas convaincue des 2 typos
et de la forme des cards + maybe put border instead of color background...?
les couleurs sont toutes prises du logo.
=> front cards

app/assets/stylesheets/pages/_boxbikeshow.scss, app/assets/stylesheets/pages/_index.scss, app/javascript/plugins/price.js, app/views/boxbikes/show.html.erb
calcul du prix non dégressif finalement car rend moins bien en l'état
front de la show en cours
=> Show price fin

app/views/boxbikes/show.html.erb
Quelques avancées sur le front du show
=> front_ongoing

app/controllers/boxbikes_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/javascript/plugins/price.js, app/views/boxbikes/_info_window.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, config/initializers/geocoder.rb
=> geocoding and search

app/assets/stylesheets/components/_card_index_boxbikes.scss, app/assets/stylesheets/components/_contract-card.scss, app/controllers/contracts_controller.rb, app/views/pages/dashboard.html.erb
Updated front end of dashboard
=> front end dashboard

app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/javascript/plugins/init_mapbox.js, app/javascript/plugins/price.js, app/views/boxbikes/show.html.erb
=> reparation_dates

app/views/boxbikes/show.html.erb
=> correction

app/views/boxbikes/show.html.erb
show copier coller de la branche précedente
=> reparation-bug

app/assets/stylesheets/pages/_boxbikeshow.scss, app/views/boxbikes/show.html.erb, app/views/pages/dashboard.html.erb
Quelques modifs de front sur show du boxbike notamment
=> last_modif

app/views/boxbikes/show.html.erb
=> last_des_lasts

app/assets/stylesheets/components/_contract-card.scss, app/views/pages/dashboard.html.erb
the final modifs for dashboard
=> Dashboard corrections2

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/boxbikes/index.html.erb, app/views/pages/home.html.erb
=> front end life is over

app/assets/stylesheets/components/_main-container.scss, app/views/boxbikes/show.html.erb
=> life is grand
